# spring.application.name=hedera-factoring-backend
hedera:
  network: testnet
  operatorId: 0.0.6351690
  operatorKey: 302e020100300506032b65700422042009f561ab2830d9e644b1e011741bb327476c83ec23a1ba224344abaf3287523e

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/factoring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update      # ? keep yours here
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080 # can override if needed
  address: 0.0.0.0