# spring.application.name=hedera-factoring-backend
hedera:
  network: testnet
  operatorId: ${HEDERA_OPERATOR_ID}
  operatorKey: ${HEDERA_OPERATOR_KEY}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/factoringdb
    username: factoring_user
    password: factoring_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update      # ? keep yours here
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect








